# Matrices


## Import

In [1]:
import numpy as np

## Matrix as a `NumPy` array

Everything in `NumPy` is an array. A matrix is also an array. Let us create a simple matrix:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [2]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Adding two matrices

Let us now add the following matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} + \textbf{B}  = \begin{bmatrix}
6 & 8\\
10 & 12
\end{bmatrix}
$$

In `NumPy`:

In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
C

array([[ 6,  8],
       [10, 12]])

## Scaling a matrix

Scaling a matrix is nothing but element-wise multiplication:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

then,

$$
3 \textbf{M} = \begin{bmatrix}
3 & 6 & 9\\
12 & 15 & 18\\
21 & 24 & 27
\end{bmatrix}
$$

In `NumPy`:

## Element-wise multiplication of matrices

Consider two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

The element-wise product is given by $\textbf{A} \odot \textbf{B}$:

$$
\textbf{C} = \textbf{A} \odot \textbf{B} = \begin{bmatrix}
5 & 12\\
21 & 32
\end{bmatrix}
$$

In `NumPy`:

## Element-wise functions of matrices

Given a matrix, we sometimes would want to apply a function to every element of the matrix. We will consider two examples.

### Example-1

For example, we may want to take the absolute value of all the elements. Let us say $f(x) = |x|$, then:

$$
\mathbf{A} = \begin{bmatrix}
-1 & 2\\
-3 & -4
\end{bmatrix}
$$

then:

$$
\begin{bmatrix}
f(-1) & f(2)\\
f(-3) & f(-4)
\end{bmatrix} =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$

In `NumPy`, this becomes:

In [4]:
A = np.array([[-1, 2], [-3, -4]])
np.abs(A)

array([[1, 2],
       [3, 4]])

### Example-2

We might want to square each element of the matrix. If $\textbf{A}$ is a matrix, then $\textbf{B}$ could be defined element-wise as follows:

$$
B_{ij} = A_{ij}^2
$$

Let us compute $\mathbf{B}$ for the following matrix:

$$
\mathbf{A} = \begin{bmatrix}
1 & \sqrt{2}\\
\sqrt{3} & 2
\end{bmatrix}
$$

In `NumPy`:

In [6]:
A = np.array([[1, np.sqrt(2)], [np.sqrt(3), 2]])
A ** 2

array([[1., 2.],
       [3., 4.]])

## Transpose of a matrix

Given a matrix $\textbf{M}$:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

then, its transpose $\textbf{M}^{T}$ is:

$$
\textbf{M}^{T} = \begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$

In `NumPy`:

In [7]:
M = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(M)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
M.T # better than np.transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

## Shape and dimension of a matrix

Matrices are "two dimensional" arrays. So all matrices in `NumPy` have array-dimension equal to two. The shape of the `NumPy` array gives what we usually call the dimension of the matrix in the linear algebra sense.

Explore these two ideas for:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{bmatrix}
$$

In `NumPy`:

In [11]:
M = np.array([[1, 2, 3], [4, 5, 6]])
print(M.shape)
print(M.ndim)
# Vectors -> (rows) -> 1-dim NP array
# Matrices -> (rows, cols) -> 2-dim NP array
# Tensors -> (rows, cols, depth) -> 3-dim NP array

(2, 3)
2


array([[1, 4],
       [2, 5],
       [3, 6]])

## Vectors as matrices

Each vector can be viewed as a matrix. Column vectors are matrices of shape $(d, 1)$. Row vectors are matrices of shape $(1, d)$. Let us look at how NumPy treats both these cases:


In [19]:
x = np.array([[1], [2], [3]])
print(x.shape)
print(x.ndim)
x

(3, 1)
2


array([[1],
       [2],
       [3]])

In [20]:
x = np.array([[1, 2, 3]])
print(x.shape)
print(x.ndim)
x

(1, 3)
2


array([[1, 2, 3]])

## Products involving matrices and vectors

We will look at the following products:
- matrix - matrix
- matrix - vector
- vector - matrix
- vector - vector

### Product of two matrices

Given two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
6 & 7\\
8 & 9\\
10 & 11
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} \times \textbf{B} = \begin{bmatrix}
52 & 58\\
124 & 139
\end{bmatrix}
$$

In `NumPy`:

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 7], [8, 9], [10, 11]])
C = A @ B
C

array([[ 52,  58],
       [124, 139]])

### Product of a matrix and a (column) vector

Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \mathbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{Ax}$ is given by:

$$
\mathbf{C} = \mathbf{A x} = \begin{bmatrix}
44\\
107\\
170
\end{bmatrix}
$$

In `NumPy`:

In [26]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([6, 7, 8])
C = A @ x
C

array([ 44, 107, 170])

### Product of a (row) vector and a matrix

Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \mathbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{x}^T \mathbf{A}$ is given by:

$$
\mathbf{C} = \mathbf{x}^T \mathbf{A} = \begin{bmatrix}
90 & 111 & 132
\end{bmatrix}
$$

In `NumPy`:

In [27]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([6, 7, 8])
x @ A

array([ 90, 111, 132])

In [28]:
np.array([6, 7, 8]).T

array([6, 7, 8])

### (Inner) Product of a (row) vector and a (column) vector

The product of a row vector and a column vector is nothing but the usual dot product:

$$
\mathbf{x}^T = \begin{bmatrix}
1 & 2 & 3
\end{bmatrix}, \quad
\mathbf{y} = \begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$

The product $\mathbf{x}^T \mathbf{y}$ is then:

$$
\mathbf{x}^T \mathbf{y} = 32
$$

In `NumPy`:

In [ ]:
x @ y

### (Outer) Product of a (column) vector and a (row) vector

The product of a column vector and a row vector is an outer product:

$$
\mathbf{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}, \quad
\mathbf{y} = \begin{bmatrix}
4 & 5 & 6
\end{bmatrix}
$$

The product $\mathbf{x} \mathbf{y}^T$ is then:

$$
\mathbf{x} \mathbf{y}^T = \begin{bmatrix}
4 & 5 & 6\\
8 & 10 & 12\\
12 & 15 & 18
\end{bmatrix}
$$

In `NumPy`:

In [29]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.outer(x, y)
# x @ y.T

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

## Matrix of zeros

In many algorithms, we might have to initialize a matrix with zeros. For example, consider a $2 \times 4$ matrix:

$$
\mathbf{M} = \begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
$$

In `NumPy`:

In [30]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matrix of ones

Similar to a matrix of zeros, we can come up with a matrix of ones.

$$
\mathbf{M} = \begin{bmatrix}
1 & 1\\
1 & 1\\
1 & 1
\end{bmatrix}
$$

In `NumPy`:

In [31]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Identity matrix

Often, we might have to deal with identity matrices. A $3 \times 3$ identity matrix is as follows:

$$
\mathbf{I} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$$

In `NumPy`:

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Diagonal matrices

Another special kind of matrix. Let us create the following matrix:

$$
\mathbf{D} = \begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 2 & 0 & 0\\
0 & 0 & 3 & 0\\
0 & 0 & 0 & 4
\end{bmatrix}
$$

In `NumPy`:

In [34]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Indexing and Slicing

Just like lists in Python, `NumPy` arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. We will look at some examples.

### Example-1: Row-slice

We will extract the third row of the matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}
$$



In `NumPy`:

In [42]:
M = np.arange(1, 11).reshape(5, 2)
M

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [43]:
M[2]

array([5, 6])

### Example-2: Column slice

Let us now extract the second column of the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [44]:
M = np.arange(1, 10).reshape(3, 3)
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
print(M[0, 1])
print(M[1, 1])
print(M[2, 1])

2
5
8


In [50]:
M[:, 1]

array([2, 5, 8])

### Example-3: Submatrix slice

Now, we want to extract the $2 \times 2$ submatrix colored in blue from $M$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & \color{blue}7 & \color{blue}8\\
9 & 10 & \color{blue}{11} & \color{blue}{12}\\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In `NumPy`:

In [52]:
M = np.arange(1, 17).reshape(4, 4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
M[1:3 , 2:4]

array([[ 7,  8],
       [11, 12]])

## Matrix algebra

There are several important matrix operations that we will list down here. The `np.linalg` module helps us perform these operations effortlessly.

## Rank, Inverse

We can get the rank of a matrix and its inverse as follows:

In [55]:
M = np.arange(1, 17).reshape(4, 4)
np.linalg.matrix_rank(M)

2

### Pseuodoinverse

The pseudoinverse $\mathbf{M}^{\dagger}$ of a matrix $\mathbf{M}$ with real entries satisfies the following properties:

- $\mathbf{M} \mathbf{M}^{\dagger} \mathbf{M} = \mathbf{M}$
- $\mathbf{M}^{\dagger} \mathbf{M} \mathbf{M} = \mathbf{M}^{\dagger}$
- $\mathbf{M} \mathbf{M}^{\dagger}$ is symmetric
- $\mathbf{M}^{\dagger} \mathbf{M}$ is symmetric

Let us go ahead and verify this for the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
3 & 6 & 9
\end{bmatrix}
$$

Note: For a complete list of properties of the pseudoinverse, check out this [link](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse#Definition).

In [57]:
M = np.array([[1, 2, 3], [3, 6, 9]])
np.linalg.matrix_rank(M)
np.linalg.pinv(M)

array([[0.00714286, 0.02142857],
       [0.01428571, 0.04285714],
       [0.02142857, 0.06428571]])

## Eigenvalues and Eigenvectors

Given a symmetric matrix $\mathbf{M}$ let us find its eigenvalues and eigenvectors:

$$
\mathbf{M} = \begin{bmatrix}
1 & 0 & -3\\
0 & 5 & 2\\
-3 & 2 & 8
\end{bmatrix}
$$

In [62]:
M = np.array([[1, 0, -3], [0, 5, 2], [-3, 2, 8]])
eigval, eigvec = np.linalg.eigh(M)

## SVD

We can compute the singular value decomposition of a matrix $\mathbf{M}$ as:

$$
\mathbf{M} = \mathbf{U} \boldsymbol{\Sigma} \mathbf{V}^T
$$

Here, the symbols have their usual meanings.

In [63]:
np.linalg.svd?